name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: $$$osArray$$$

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    $$$extraBuildSteps$$$

    - name: Setup Deno
      if: runner.os == 'Linux'
      uses: denoland/setup-deno@v1

    - name: run user build script
      run: |
        deno run -A userBuild.ts

    - name: Upload artifactss
      uses: svenstaro/upload-release-action@v2
      with:
        file: $$$targetFile$$$
        overwrite: true
